### ISSUE TITLE
ov50 - Security Notice with Weather on

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/watchdog_pi#108]
There Norton Security Notices activated from on of the Weather alarms when setup. 
The computer hits high cpu and Norton notifies and also block outside access.
What is the alarm doing exactly?

I tried to get a screenshot, but don't seem to have it.

**Comment by seandepagnier** [comment]
Which alarm?

It may trigger the alarm if it fails to receive data depending on the
alarm settings.   If your high cpu slows the system enough, it could
cause this.

**Comment by rgleason** [comment]
I'll dig when I have a chance.

**Comment by rgleason** [comment]
an Anomoly
