### ISSUE TITLE
error compiling on ubuntu 14.04 and raspbian (raspberry)

### ISSUE THREAD

**Issue by sailoog** [seandepagnier/watchdog_pi#11]
ubuntu output:

[ 43%] Building CXX object CMakeFiles/watchdog_pi.dir/src/WatchdogDialog.cpp.o
/home/sailoog/watchdog_pi/src/WatchdogDialog.cpp: In constructor ‘WatchdogDialog::WatchdogDialog(watchdog_pi&, wxWindow*)’:
/home/sailoog/watchdog_pi/src/WatchdogDialog.cpp:68:59: error: invalid use of incomplete type ‘class wxImageList’
     wxImageList *imglist = new wxImageList(16, 16, true, 1);
                                                           ^
In file included from /usr/include/wx-2.8/wx/listctrl.h:36:0,
                 from /usr/include/wx-2.8/wx/generic/filedlgg.h:15,
                 from /usr/include/wx-2.8/wx/gtk/filedlg.h:13,
                 from /usr/include/wx-2.8/wx/filedlg.h:210,
                 from /usr/include/wx-2.8/wx/wx.h:94,
                 from /home/sailoog/watchdog_pi/src/watchdog_pi.h:30,
                 from /home/sailoog/watchdog_pi/src/WatchdogDialog.cpp:27:
/usr/include/wx-2.8/wx/generic/listctrl.h:16:24: error: forward declaration of ‘class wxImageList’
 class WXDLLIMPEXP_CORE wxImageList;
                        ^
/home/sailoog/watchdog_pi/src/WatchdogDialog.cpp:69:12: error: invalid use of incomplete type ‘class wxImageList’
     imglist->Add(wxBitmap(check_xpm));
            ^
In file included from /usr/include/wx-2.8/wx/listctrl.h:36:0,
                 from /usr/include/wx-2.8/wx/generic/filedlgg.h:15,
                 from /usr/include/wx-2.8/wx/gtk/filedlg.h:13,
                 from /usr/include/wx-2.8/wx/filedlg.h:210,
                 from /usr/include/wx-2.8/wx/wx.h:94,
                 from /home/sailoog/watchdog_pi/src/watchdog_pi.h:30,
                 from /home/sailoog/watchdog_pi/src/WatchdogDialog.cpp:27:
/usr/include/wx-2.8/wx/generic/listctrl.h:16:24: error: forward declaration of ‘class wxImageList’
 class WXDLLIMPEXP_CORE wxImageList;
                        ^
/home/sailoog/watchdog_pi/src/WatchdogDialog.cpp:70:41: error: ‘wxIMAGE_LIST_SMALL’ was not declared in this scope
     m_lStatus->AssignImageList(imglist, wxIMAGE_LIST_SMALL);
                                         ^
make[2]: *** [CMakeFiles/watchdog_pi.dir/src/WatchdogDialog.cpp.o] Error 1
make[1]: *** [CMakeFiles/watchdog_pi.dir/all] Error 2
make: *** [all] Error 2

**Comment by seandepagnier** [comment]
you are still using wx-2.8... this won't be supported much longer but
I just fixed it for now.

**Comment by sailoog** [comment]
OK.
There is no problem updating to wx-3 on ubuntu but I am afraid one must compile it on Raspbian :(
Thanks!
