### ISSUE TITLE
Use of  message box causes anomylies in Mac and Win

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/watchdog_pi#110]
http://www.cruisersforum.com/forums/f134/watchdog-plugin-150313.html#post2966637
I'm having an alarm configuration issue. Once an alarm condition is met (inclusion zone exceeded), it will alarm by playing a sound and giving me the message box but after it plays the sound file once, it doesn't repeat it even though the condition is still met. 

http://www.cruisersforum.com/forums/f134/watchdog-plugin-150313.html#post2966681
> It only happens if you choose to have a message box. The alarm (sound file) will play and the message box will display. After the sound file plays once, the message box has to be acknowledged and then the alarm will sound again.
> 
> This is messy (but different) on Windows where the sound will repeat but you'll also get a stack of message boxes on top of each other that you have to individually dismiss.
> 
> Without the message box, the alarm sound repeats. 
>

**Comment by pa2wlt** [comment]
Rick, Sean: I notice exactly the same behaviour on my Windows 10 machine (OpenCPN 5.0.0+9065270). I also notice that if you choose to have a message box, every new alarm will cause a new message box. So for the same alarm you might end up having tens of message boxes over another. Wouldn't it be easier for the user to only see a new message box, if the previous message box has been closed?

**Comment by rgleason** [comment]
Yes

**Comment by rgleason** [comment]
Interface has changed. Closing
