### ISSUE TITLE
In flatpak, Watchdog doesn't create   .var/org.opencpn.OpenCpn/config/opencpn/plugins/watchdog

### ISSUE THREAD

**Issue by filochard** [seandepagnier/watchdog_pi#116]
Inside flatpak watchdog can't write user's owned files in the right place
because there is no 
/home/username/.var/org.opencpn.OpenCpn/**config**/opencpn/plugins/**watchdog** directory

If there's a classical linux installation besides flatpak installation, the user's created files are wrongly written in the linux directory : 
/home/username/.opencpn/plugins/wathdog   !!! 
NB The readonly data files are in the right place : 
/home/username/.var/app/org.opencpn.OpenCPN/**data**/opencpn/plugins/**watchdog_pi**/data/

That was found by investigating an issue of an other plugin
https://github.com/rgleason/LogbookKonni_pi/issues/6#issuecomment-830917980

This may concern other plugins
https://github.com/OpenCPN/OpenCPN/issues/2256

**Comment by filochard** [comment]
sorry for the noise
this issue is for 
https://github.com/rgleason/watchdog_pi/

**Comment by rgleason** [comment]
I believe this should be fixed in v 2.4.70.
Please close.

**Comment by filochard** [comment]
Hi Rick
It's OK now for flatpak
(and for legacy installation )

**Comment by rgleason** [comment]
OK, good. Then please close it. Thanks.

**Comment by rgleason** [comment]
@filochard   Please close this now. I can't close it. It needs to be closed by you!!!!!
