### ISSUE TITLE
Realign Repositories  - Check Sean's commits, squash testplugin history, make a PR

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/watchdog_pi#120]
### Depth   -added Jan 15 2021  

- Sean's - https://github.com/seandepagnier/watchdog_pi/commit/29cfd7784778d45896e7495e5a9aff84410a994d
- rgleason - added manually here https://github.com/rgleason/watchdog_pi/commit/49d8ae45af7ca6bce1d13f3870bd63239325f65c

### update pypilot support  -added Aug 25 2021

- Sean - https://github.com/seandepagnier/watchdog_pi/commit/7f7c655aba5e49c5771a3c6ff927e0d44d5aa27f

- rgleason -  I don't find this commit in my repository.  I need to get this manually commited.

Then I would like to simplify the testplugin history (squash it) and make a commit back to Sean's repository so that we are current.

**Comment by leamas** [comment]
The squashing of this history is actually not trivial. I need to take a look at it. Stay tuned.

As long as you think yuo can do it manually, so fine. That said, I'm pretty convinced I can't in non-trivial cases. That is, to make correct in a reasonable time...

**Comment by rgleason** [comment]
Thankyou Alec.

**Comment by rgleason** [comment]
Closing.  I've looked into this and think I can fix the divergence.
