### ISSUE TITLE
Pb with Watchdog and Draw on Opencpn 5.8.4

### ISSUE THREAD

**Issue by kinefou** [seandepagnier/watchdog_pi#136]
Good morning,

Opencpn v:5.8.4
Watchdog v:2.4.107
Draw v: 1.8.49

I have a problem with the latest versions of watchdog and draw. I define a protection zone around my boat to detect a cargo ship entering my area using its AIS.
Everything worked perfectly with Openplotter 2 but since my move to Openplotter 3 and Opencpn 5.8.4, there is apparently no AIS detection.
Attached is a screenshot showing a freighter in my area, but not detected!
Does anyone have a solution to this problem?
for the tests at home, I connected opencpn to sinagot.net port 2948 in GPSD to have targets and I positioned my boat on the path of a cargo ship!
Thank you very much for a response
Sincerely
Thierry
![Capture d’écran du 2024-04-17 14-48-45](https://github.com/seandepagnier/watchdog_pi/assets/107059046/6e014bbb-930c-4723-9ff9-8613e5bc7cb6)

**Comment by jongough** [comment]
I have now setup my system running on Ubuntu and tested what is going on. It would appear that watchdog is not processing the AIS messages successfully end ending up with a lat/lon of 0/0 which is then passed to ODraw to check if the lat/lon is within the guard zone, which in most cases it will not be.

I have created a pull request on watchdog_pi to look for the new "AisDecoder" source message. Hopefully this will work. It seems to on my linux system.

**Comment by kinefou** [comment]
thank you Jongough for your solution, but how can I apply it on my Raspberry pi? Should I wait for the next plugin update?
Sincerely
Thierry

**Comment by jongough** [comment]
Looking at the repositories, this change 'may' have made it through. It is version 2.4.107.0, which is the same version number as the last release. You could try uninstalling watchdog, then reinstall it making sure you download the version from the internet and don't use the version in your plugin cache (you will need to find the `plugins/cache` directory and delete the watchdog file in there). I am not sure why the version number didn't change, but....

**Comment by kinefou** [comment]
Thank you Jongough for your explanations, but unfortunately, it doesn't work for me. Maybe the repository hasn't been updated yet! I'll try again tomorrow.
Sincerely

**Comment by jongough** [comment]
I have checked and whilst the change for AIS has been incorporated there is only a windows build currently available. I am chasing up about the other builds.

**Comment by kinefou** [comment]
Thank you very much for your research! Could you let me know when a linux version will be available? I will try the Windows version.
Sincerely
Thierry

**Comment by jongough** [comment]
Hopefully the version that will install on all platforms should be available shortly. It requires my change to be incorporated and the plugin files made available.

**Comment by kinefou** [comment]
Thanks a lot !!

**Comment by jongough** [comment]
The changed plugin should be available from the master repository now. You will need to update the master catalog and then update the watchdog plugin, 2.4.110.0 is the one that should have the fix in it.

**Comment by kinefou** [comment]
Thank you Jongough for your efficiency and availability! version 2.4.110.0 works correctly on my computer.
Sincerely
Thierry
