### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by mschiff** [seandepagnier/watchdog_pi#4]
Hi!

It would be very usefull to have tagged releases, so the source for a specific version of th eplugin can be downloaded. Please add a release/tag for your released versions. This makes packaging a lot easier. 

I'd like to package this plugin for Gentoo Linux and for that it requires a reliable specific download URL for the releases. 

Thanks in advance!

**Comment by mschiff** [comment]
ping?

**Comment by SaltyPaws** [comment]
Hi Sean,

There is a lot going on in my life right now, but I hope to dedicate some
time to this in the coming months. Thanks for follwoing up!

**Comment by rgleason** [comment]
It is time to close this. There are many tags made since this.
Sean can you close this?

**Comment by rgleason** [comment]
Sean, Please close this, I cannot.

**Comment by rgleason** [comment]
Please close this. Sean
