### ISSUE TITLE
Enhancement request...Last chance warning for Deadman alarm

### ISSUE THREAD

**Issue by NAHANNIV** [seandepagnier/watchdog_pi#5]
It would be great if there could be two stages to the Deadman alarm:

1st - a last chance warning to remind/wake-up the on watch.

2nd - alarm to wake the offwatch crew if the onwatch did not respond to the warning alarm.

Thanks for the excellent plugin,
JM.

**Comment by seandepagnier** [comment]
So you mean a separate action with an extended timeout?  It would just run
a different command, like to output sound to a different device?

**Comment by NAHANNIV** [comment]
Yes, what I would do is have a quiet chime or something to remind/wake-up the on-watch crew for the first alarm. Then a louder obnoxious wake the whole crew alarm (possibly another device) if the first reminder is not acknowledged.

Thanks,
JM.

**Comment by NAHANNIV** [comment]
Thanks, great simple implementation !
