### ISSUE TITLE
po-files from Crowdin Feb 14

### ISSUE THREAD

**Issue by Hakansv** [seandepagnier/watchdog_pi#52]
Sean or Jon
Attached are po-files from Crowdin where translation levels are more than 45%.
Please copy these files since a pull request creates conflicts on the existing files created by Gettext instead of Crowdin. I think it's more job to solve the conflicts then this copying. 
Next po-update will run smother by a PR when all files are created in Crowdin.

My intention to include other then 100% translated files is to force possible translators to a Crowdin completion. :)
If you disagree you could choice to copy only: es, et, fi, fr, nl, pt, sv -.po. These are >99%
Håkan

[po.zip](https://github.com/seandepagnier/watchdog_pi/files/129685/po.zip)

**Comment by jongough** [comment]
Håkan,
   I have put all the files you supplied into the plugin. Partial translations are better than none, so....

Jon
