### ISSUE TITLE
please fix GZprop.h name

### ISSUE THREAD

**Issue by mbouyer** [seandepagnier/watchdog_pi#78]
hello,
you
#include "GZprop.h"
but in the source there is GZProp.h (note P vs p). This cause a build failure on unix systems (or any system with case-sensitive filesystem).
Attached patch fi
[patch-src_ocpn_draw_pi.cpp.txt](https://github.com/seandepagnier/watchdog_pi/files/312295/patch-src_ocpn_draw_pi.cpp.txt)

xes the build for me.

**Comment by jongough** [comment]
Fixed in patch 1.1.10 of ocpn_draw_pi. This is one of the problems of using CIFS shares for the source code where both windows and unix have to share files. By the way, this issue should have been raised in the ocpn_draw_pi project on git (http://github.com/jongough/ocpn_draw_pi), but thanks for raising it.
Jon

**Comment by mbouyer** [comment]
On Mon, Jun 13, 2016 at 02:23:03PM -0700, jongough wrote:
> Fixed in patch 1.1.10 of ocpn_draw_pi. This is one of the problems of using CIFS shares for the source code where both windows and unix have to share files. By the way, this issue should have been raised in the ocpn_draw_pi project on git (http://github.com/jongough/ocpn_draw_pi), but thanks for raising it.
> Jon
> 

Ops, sorry I used the wrong tab in my firefox (and so the
wrong github project). I'll me more carefull next time.

-- 
Manuel Bouyer <bouyer@antioche.eu.org>
     NetBSD: 26 ans d'experience feront toujours la difference
--

**Comment by mbouyer** [comment]
jongough fixed it, and I can confirm it's fixed (and this has been opened in the wrong repo :(
