### ISSUE TITLE
Sumary table shows sound even when sound non is selected

### ISSUE THREAD

**Issue by dominig** [seandepagnier/watchdog_pi#88]
The Watch dog summary table show an indication of sound as soon as Sound has been selected even if the sound selection is 'None' (which is the default).

Sound should only be listed when sound is selected and that a sound is configured.
![screenshot_20170412_165540](https://cloud.githubusercontent.com/assets/1193120/24964340/4d51c376-1fa1-11e7-9ac1-c0da72bfde53.png)

**Comment by rgleason** [comment]
In ov50 this table is no longer valid. I think this needs to be closed. 
Dominiq can you close it?  Sean?

**Comment by dominig** [comment]
Thanks for the change
