### ISSUE TITLE
Default alarm sound should not be none

### ISSUE THREAD

**Issue by dominig** [seandepagnier/watchdog_pi#89]
At least one default alarm should be included with the plugin in order to be used as default.
Should be a strong one, basic but efficient.

**Comment by seandepagnier** [comment]
Which alarm?

**Comment by dominig** [comment]
Sean,
Sean,
any alarm related to the Watchdog. I faced the issue with the anchor alarm where I thought that I had a sound configured but in reality I had lost it.
But my quick tests let me to believe that the issue is more generic.

**Comment by rgleason** [comment]
I think this is solved. It is using the Opencpn bells right now in the Sounds folder.
You could add sounds if you like and select from those files!
This is not an issue anymore in my opinion.
Can we close it?

**Comment by rgleason** [comment]
This can be closed now, I believe.  Sean I can't close it.
