### ISSUE TITLE
77cec33 fix problem with command checkbox  - does not compile WIN

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/watchdog_pi#9]
C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\build>git branch -va
* master                77cec33 fix problem with command checkbox always checked
  remotes/origin/HEAD   -> origin/master
  remotes/origin/master 77cec33 fix problem with command checkbox always checked

Build FAILED.

"C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\build\ALL_BUILD.vcxproj" (default target) (
1) ->
"C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\build\watchdog_pi.vcxproj" (default target)
 (3) ->
(ClCompile target) ->
  C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\src\wddc.cpp(388): warning C4390: ';' : em
pty controlled statement found; is this the intent? [C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-wat
chdog_pi\build\watchdog_pi.vcxproj]

"C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\build\ALL_BUILD.vcxproj" (default target) (
1) ->
"C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\build\watchdog_pi.vcxproj" (default target)
 (3) ->
(ClCompile target) ->
  C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\src\wddc.cpp(363): error C2065: 'GL_SMOOTH
_LINE_WIDTH_RANGE' : undeclared identifier [C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\
build\watchdog_pi.vcxproj]
  C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\src\wddc.cpp(372): error C2065: 'GL_ALIASE
D_LINE_WIDTH_RANGE' : undeclared identifier [C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi
\build\watchdog_pi.vcxproj]
  C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\src\wddc.cpp(557): error C2065: 'GL_SMOOTH
_LINE_WIDTH_RANGE' : undeclared identifier [C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\
build\watchdog_pi.vcxproj]
  C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi\src\wddc.cpp(566): error C2065: 'GL_ALIASE
D_LINE_WIDTH_RANGE' : undeclared identifier [C:\Data-Dart\Up-Soft\Navigation\o-plugin\s-watchdog_pi
\build\watchdog_pi.vcxproj]

    1 Warning(s)
    4 Error(s)

Also tried most current opencpn.lib from recent git v4.1.602

**Comment by rgleason** [comment]
Deleted all under build except opencpn.lib.  then at VS13 command prompt  cmake -T v120_xp ..
Get same results.

**Comment by seandepagnier** [comment]
Rick,

What happens if you copy the "GL" directory from
OpenCPN/include/GL/gl.h into watchdog_pi/src/GL to make
watchdog_pi/src/GL/gl.h?

Sean

**Comment by rgleason** [comment]
It compiles!

**Comment by seandepagnier** [comment]
great you can make a pull request if you want or eventually I will
(can't at the moment)
