### ISSUE TITLE
Sound level should be configurable

### ISSUE THREAD

**Issue by dominig** [seandepagnier/watchdog_pi#90]
Watchdog is, for me the most useful plugin from OpenCPN but the fact that anyone on the cboat can change the level of audio (to listen at some music) and by such action reduce the level of my alarms is worrying.
I would expect the watch dog to be able to use pulse setting to ask for a volume controle and re-inforce it before playing the alarm.
At least to get out of any mute setting or play via the Alarm channel (like the ringing on an incoming call).

**Comment by seandepagnier** [comment]
Yes. well I would consider low priority.  If you need it right now, you can implement this via an external command.

**Comment by dominig** [comment]
The it can be done by an external command but that is pretty much out of reach for most of OpenCPN Users.

**Comment by seandepagnier** [comment]
so, does the plugin need to mute all other sounds as well as change the volume for it's own sound?

I can not find in portaudio a way to change volume.  Any solution would be non-portable.

**Comment by dominig** [comment]
Sean,
Muting other output is for me a nice to have but not required.
I would just put the volume to configure value in %

Portaudio API is very poor but wx and qt both provide portable volume control API.

 - http://docs.wxwidgets.org/trunk/classwx_media_ctrl.html#a4451b025e1b08a7500f45d35a13bad2c
 - http://docs.wxwidgets.org/trunk/classwx_media_ctrl.html#a4451b025e1b08a7500f45d35a13bad2c
Regards
Dominig

**Comment by rgleason** [comment]
Dominig,
Another good idea. 
Opencpn ov50 has Sound changes to be considered.

**Comment by rgleason** [comment]
I think this is outdated.  The sound files can be picked.. You can add alarm sound files and use them.  The sound level can be controlled from your Sound   Speaker/Headphone.

Sean will accept additional PR's regarding this.
I think this should be closed as it is old.

**Comment by rgleason** [comment]
Sean, please close this.
