### ISSUE TITLE
Keep losing the configured sound

### ISSUE THREAD

**Issue by dominig** [seandepagnier/watchdog_pi#92]
On Linux (at least), the configured sound is not saved anywhere and most every time we get out of the menu configuration in such a way that we never know if the sound will work on not.
The  bug https://github.com/seandepagnier/watchdog_pi/issues/88 makes the problem worse.

Configured sound are saved in the file 
 .opencpn/plugins/watchdog/WatchdogConfiguration.xml
But that seems to not read at initialisation.

**Comment by rgleason** [comment]
Dominig, give ov50 version a try please.

**Comment by dominig** [comment]
Rick
Busy the coming days, but I will get a look as soon as I find some time.
Thanks.

**Comment by rgleason** [comment]
Dominig and Sean, this should be closed. Very old.
