### ISSUE TITLE
Adding MMSI & ship name as alarm command line arguments

### ISSUE THREAD

**Issue by pcoulombeau** [seandepagnier/watchdog_pi#98]
Hello,
I am new to opencpn and watchdog, apologize if these questions are already answered somewhere although I spent some time looking for answers first. 

New feature: I have wrote a short code to add MMSI & ship name as new arguments for alarm command. Indeed I would like to record MMSI crossing the exclusion zone in emails, and this seems the easiest way to do.

Build issue: Now I am stucked in trying to execute the watchdog_pi.dll with mainstream OpenCPN 4.8.4.
I have been using both watchdog_pi version 2.2.001 (April 11) and 2.1.000 (Feb 15), with opencpn.lib (4.8.2, 4.8.4), wxWidgets-3.0.4 and 3.1.1
It fails at runtime reporting compatibility issue with version 1.
Under Windows 10, VS2017, building with cmake.

I would appreciate some guidance to fix this build issue (in other words I am simply trying to execute a rebuilt from scratch watchdog_pi for 4.8.4 version)
Thanks much,
Pierre

**Comment by jongough** [comment]
Hi,
   I have just built the watchdog plugin from the latest source in git for both windows (win 10 vs2017) and linux. I have run it in windows 10 using OCPN 4.99.0 and widgets 3.0.2 and it appears to be working OK. Try using an earlier version of widgets and see how that goes.

   What are you trying to achieve as the MMSI and ship name are already displayed in the message for AIS targets in guard zones?

Regards
Jon

**Comment by rgleason** [comment]
Can we please close this?   pcoulombeau 
I believe this request is covered by use of Watchdog with Ocpn_Draw's boundary functions.

Sean you can close this. I can't.

**Comment by seandepagnier** [comment]
Does he want to alarm if a particular ship crosses a boundary?   I
don't think this is implemented.

**Comment by rgleason** [comment]
He doesn't mind getting hit by other ships, just not that particular one? grin
Or is this just an friend's arrival notice when you are waiting for someone?
Trying to figure out the uses.  Maybe its useful, but a minor case I think.

**Comment by pcoulombeau** [comment]
Hello
Thanks first for your review of this request.
The use case here is to track ships that enter zones close to sensitive,
forbidden or even dangerous areas, log this through external command line
tools into a database.
Ideally it could be implemented by using keywords, e.g. "%mmsi" or
"%ship_name", added to the command line arguments.
I may have missed other way to do that ?
Thanks much
Pierre

Le sam. 2 mars 2019 à 8:59 PM, Rick Gleason <notifications@github.com> a
écrit :

**Comment by rgleason** [comment]
Ok so this is a Govt Security/Environmental Monitering Alarm
Makes sense now.

**Comment by rgleason** [comment]
Sean wrote:
Does he want to alarm if a particular ship crosses a boundary?   I
don't think this is implemented.   - Yes

Pcoulombeau wrote:
```
The use case here is to track ships that enter zones close to sensitive,
forbidden or even dangerous areas, log this through external command line
tools into a database.
Ideally it could be implemented by using keywords, e.g. "%mmsi" or
"%ship_name", added to the command line arguments.
I may have missed other way to do that ?
```

Pcoulombeau where is your code for this on github?

**Comment by rgleason** [comment]
@pcoulombeau  You haven't responded to the above. If this is a serious RFE Request for Enhancement, then you need to participate, otherwise we will close this.
